- name: Actualizar servidores Ubuntu
  apt:
   update_cache: "yes"
   name: "*"
   state: latest
  become: true
  when: ansible_os_family == "Debian"
  
- name: Actualizar servidores CentOs
  yum:
   name: "*"
   state: latest
  become: true
  when: ansible_os_family == "RedHat"
