- name: Agregando PHP PPA...
  apt:
   name: software-properties-common
   state: present
  become: true
  when: ansible_os_family == "Debian"

- name: Agregando repositorio PPA...
  ansible.builtin.command: add-apt-repository ppa:ondrej/php -y
  become: true
  when: ansible_os_family == "Debian" 

- name: Instalando PHP...
  ansible.builtin.command: apt install php8.0 libapache2-mod-php8.0 -y
  become: true
  when: ansible_os_family == "Debian" 