- name: Agregando PHP PPA...
  apt:
   name: software-properties-common
   state: present
  become: true
  when: ansible_os_family == "Debian"

- name: Agregando repositorio PPA...
  ansible.builtin.command: add-apt-repository ppa:ondrej/php -y
  become: true
  when: ansible_os_family == "Debian" 

- name: Instalando PHP...
  ansible.builtin.command: apt install php8.0 libapache2-mod-php8.0 -y
  become: true
  when: ansible_os_family == "Debian" 

- name: Reiniciando apache httpd...
  ansible.builtin.service:
   name: apache2
   state: restarted
  become: true
  when: ansible_os_family == "Debian" 

- name: Create PHP Info Page...
  file:
   path: "/var/www/html/info.php"
   state: touch
  become: true
  when: ansible_os_family == "Debian" 

- name: Add content to file PHP Info...
  copy:
   dest: "/var/www/html/info.php"
   content:
    <?php
    phpinfo();
    ?>
  become: true
  when: ansible_os_family == "Debian" 



